import { ProductItem } from "@/types";

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: "prod-elma-01",
    name: "Elma",
    slug: "elma",
    sku: "RAZ-ELM-01",
    price: 2350,
    compareAtPrice: 2645,
    category: "UNISEX",
    size: "30ml EDP",
    stock: 50,
    featured: true,
    active: true,
    shortDescription: "Warm golden sunlight captured in glass.",
    description:
      "Elma blooms with the delicate sweetness of apple blossom and bright bergamot, unfolding into a warm amber heart. A radiant scent that captures golden sunlight in a bottle. Handcrafted for those who appreciate quiet refinement and luminous depth.",
    fragranceNotes: "Apple blossom, Bergamot, Rose absolute, Amber, White cedar, Musk",
    topNotes: "Apple blossom, Bergamot",
    middleNotes: "Rose absolute, Amber",
    baseNotes: "White cedar, Musk",
    images: [
      {
        imageUrl: "/razen-assets/relma1.png",
        altText: "Elma Eau De Parfum Bottle",
        sortOrder: 0,
      },
      {
        imageUrl: "/razen-assets/hs2.png",
        altText: "Elma Fragrance Notes Texture",
        sortOrder: 1,
      },
    ],
  },
  {
    id: "prod-mavi-02",
    name: "Mavi",
    slug: "mavi",
    sku: "RAZ-MAV-02",
    price: 2350,
    compareAtPrice: 2645,
    category: "UNISEX",
    size: "30ml EDP",
    stock: 45,
    featured: true,
    active: true,
    shortDescription: "Cool ocean breeze and coastal tranquility.",
    description:
      "Mavi opens with the crisp, bracing energy of sea salt and bergamot, settling into a tranquil driftwood heart. A scent that evokes the serenity of a cool ocean breeze, untouched shores, and effortless distinction.",
    fragranceNotes: "Sea salt, Bergamot, Driftwood, Blue lotus, Oakmoss, Ambergris",
    topNotes: "Sea salt, Bergamot",
    middleNotes: "Driftwood, Blue lotus",
    baseNotes: "Oakmoss, Ambergris",
    images: [
      {
        imageUrl: "/razen-assets/rmavi1.png",
        altText: "Mavi Eau De Parfum Bottle",
        sortOrder: 0,
      },
      {
        imageUrl: "/razen-assets/hs3.png",
        altText: "Mavi Fragrance Notes Texture",
        sortOrder: 1,
      },
    ],
  },
  {
    id: "prod-serin-03",
    name: "Serin",
    slug: "serin",
    sku: "RAZ-SER-03",
    price: 2350,
    compareAtPrice: 2645,
    category: "UNISEX",
    size: "30ml EDP",
    stock: 40,
    featured: true,
    active: true,
    shortDescription: "Dark, enigmatic, matte elegance.",
    description:
      "Serin is a deep, enigmatic fragrance where smoky vanilla meets the raw intensity of black oud and subtle leather. A daring composition that leaves a matte, mysterious trail for those whose presence whispers volume.",
    fragranceNotes: "Black oud, Vetiver, Smoked vanilla, Leather, Sandalwood, Incense",
    topNotes: "Black oud, Vetiver",
    middleNotes: "Smoked vanilla, Leather",
    baseNotes: "Sandalwood, Incense",
    images: [
      {
        imageUrl: "/razen-assets/rserin1.png",
        altText: "Serin Eau De Parfum Bottle",
        sortOrder: 0,
      },
      {
        imageUrl: "/razen-assets/hs1.png",
        altText: "Serin Fragrance Notes Texture",
        sortOrder: 1,
      },
    ],
  },
];
